"""
This is a makeapp.py script generated by py2applet

Usage:
    python makeapp.py py2app
"""
import glob
from setuptools import setup

WAVS = glob.glob('scripts/*.wav')
APP = ['scripts/sip_audio_session.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
           'site_packages': True,
           'resources': WAVS,
           'includes': ['dns.*', 'application.*', 'pypjua.*'],
           'packages': ['dns', 'application', 'pypjua']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
