#!/bin/sh

self='pypjua'
name='PyPjUA SIP client'
script='pypjua/engine.py'
pkgignore=".pkgignore"
style=""

if [ ! -f $script ]; then
    echo "Run this program inside the $name directory"
    exit 1
fi

dirname=`basename $PWD`
basedir=`dirname  $PWD`

version=`grep version pypjua/__init__.py|cut -f 2 -d "\""`
archive="$self-$version$style.tar.gz"

if [ "$dirname" != "$self" ]; then
    create=1
else
    create=0
fi

if [ $create -eq 1 ]; then
   (cd ../; ln -s "$dirname" $self)
fi

echo "Creating $archive"

GZIP=--best
tar --exclude-from=$pkgignore --directory ../ -zchf "$archive" $self

if [ $create -eq 1 ]; then
   rm ../$self
fi

